name: wa_blast
description: "Wave Bizz App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/wave-biz-logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/wave-biz-logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
