// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_3pU40tTm3Ce4L6ElkIG4mfK5z8W9EpY',
    appId: '1:1094236657957:web:9b539ad13606370e71e2cc',
    messagingSenderId: '1094236657957',
    projectId: 'wave-biz',
    authDomain: 'wave-biz.firebaseapp.com',
    storageBucket: 'wave-biz.firebasestorage.app',
    measurementId: 'G-73LPDBCXG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGH0kNKRIxiknB45kcNEbcPjg0GQLtc0',
    appId: '1:1094236657957:android:65d42710d688500571e2cc',
    messagingSenderId: '1094236657957',
    projectId: 'wave-biz',
    storageBucket: 'wave-biz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQfUNHo63MfzjThBj6f53FQESJBaetI54',
    appId: '1:1094236657957:ios:2590cb769d44877171e2cc',
    messagingSenderId: '1094236657957',
    projectId: 'wave-biz',
    storageBucket: 'wave-biz.firebasestorage.app',
    androidClientId: '1094236657957-i6d3ihcv3mcmqktr2resn8ts38mn41qf.apps.googleusercontent.com',
    iosClientId: '1094236657957-5s63dhut8d49aomv91gefd9srg5pl23k.apps.googleusercontent.com',
    iosBundleId: 'com.wave.updev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQfUNHo63MfzjThBj6f53FQESJBaetI54',
    appId: '1:1094236657957:ios:8af6ee6f320d68be71e2cc',
    messagingSenderId: '1094236657957',
    projectId: 'wave-biz',
    storageBucket: 'wave-biz.firebasestorage.app',
    androidClientId: '1094236657957-i6d3ihcv3mcmqktr2resn8ts38mn41qf.apps.googleusercontent.com',
    iosClientId: '1094236657957-jab6lsa4tcdtpl9u1s0ppt7o34ujk8kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.waBlast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_3pU40tTm3Ce4L6ElkIG4mfK5z8W9EpY',
    appId: '1:1094236657957:web:3313c2394e0ae49871e2cc',
    messagingSenderId: '1094236657957',
    projectId: 'wave-biz',
    authDomain: 'wave-biz.firebaseapp.com',
    storageBucket: 'wave-biz.firebasestorage.app',
    measurementId: 'G-8F3DQ5T0FL',
  );

}