platform :ios, '14.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug'        => :debug,
  'Profile'      => :release,
  'Release'      => :release,
  'Debug-dev'    => :debug,
  'Release-dev'  => :release,
  'Debug-prod'   => :debug,
  'Release-prod' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  # Static frameworks: aman untuk FlutterFire terbaru & kebanyakan pods
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Midtrans (punyamu) — biarkan apa adanya
  pod 'MidtransKit',     :git => 'https://github.com/veritrans/Veritrans-ios-sdk.git', :tag => '1.28.0'
  pod 'MidtransCoreKit', :git => 'https://github.com/veritrans/Veritrans-ios-sdk.git', :tag => '1.28.0'
end

target 'RunnerTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Paksa semua Pods ikut iOS 14.0 (sinkron dengan baris platform di atas)
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      # (Opsional) kalau simulator arm64 bermasalah, aktifkan baris berikut:
      # config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
